### ISSUE TITLE
Cluster cannot start with older versions of k8s

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#10122]
After merging https://github.com/kubernetes/kops/pull/10048, the new way of installing Docker is conflicting with the pre-installed Docker in the `kope.io` images.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-k8s-1-15/1320685447990480896

A similar problem existed in 1.17 and was fixed in https://github.com/kubernetes-sigs/image-builder/pull/273, by just copying the Docker deb files to `/var/cache/nodeup/packages` and letting kOps install them if the hash matches.

All `kope.io` images from 1.11 to 1.16, maybe also 1.17.

**Comment by rifelpet** [comment]
This issue is impacting kubernetes 1.17 as well: https://testgrid.k8s.io/kops-versions#kops-aws-k8s-1.17

https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-k8s-1-17/1344395270774853632/artifacts/18.193.88.194/protokube.log

```
Starting Kubernetes Protokube Service...
Started Kubernetes Protokube Service.
ctr: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/dbus\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v2.task/k8s.io/protokube/rootfs\\\" at \\\"/var/run/dbus\\\" caused \\\"stat /var/run/dbus: no such file or directory\\\"\"": unknown
protokube.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by hakman** [comment]
Yes, dbus should be installed on those images.
Ref: https://github.com/kubernetes-sigs/image-builder/issues/130

**Comment by atam003** [comment]
I am using kops1.19 +Kubernetes 1.16. I tried using image latest available kops image "kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-07-20". I see this issue.
Is there any latest published image of kops which can be used?

**Comment by hakman** [comment]
@atam003 until 1.19 is released, you can use the official Debian 9 [image](https://kops.sigs.k8s.io/operations/images/#debian-9-stretch) or the Ubuntu 20.04 [image](https://kops.sigs.k8s.io/operations/images/#ubuntu-2004-focal).

**Comment by sonowz** [comment]
Is there any workaround with this issue?
I'm using kops 1.19-beta3, Kubernetes 1.18, and my AMI is Ubuntu 18.04 with Docker pre-installed.
Then struck into same error as #10492.
What should I do in order for the AMI to work?

**Comment by hakman** [comment]
@sonowz can you explain a bit more why Ubuntu 18.04 and why docker pre-installed?

As for workaround, you could try with:
```yaml
  containerd:
    skipInstall: true
  docker:
    skipInstall: true
```

The issue should be fixed once 1.19 is released later this week (I hope).

**Comment by sonowz** [comment]
There's no reason to use 18.04, it's just a version I'm currently using.
The reasons why Docker is pre-installed are the following:
- [nvidia-container-runtime](https://github.com/NVIDIA/nvidia-container-runtime) should be configured as default runtime
- Some images should be stored in AMI due to its gigantic size (~20GB)

> The issue should be fixed once 1.19 is released later this week (I hope).

That's good to hear! I'm looking forward to it.

**Comment by hakman** [comment]
Thanks for explaining. You may also disable the Docker and containerd services in the AMI. kOps will start them later.

**Comment by sonowz** [comment]
Disabling autostart of Docker and containerd service works! Thanks a lot 👍

**Comment by atam003** [comment]
@hakman 
I see kops 1.19 is released today. I tried using it. I see the issue is still there ... Please note that I am using Kubernetes 1.16.9 version.

**Comment by hakman** [comment]
Thanks @atam003, https://github.com/kubernetes/kops/pull/10691 should fix this in 1.19 also.

**Comment by atam003** [comment]
@hakman I still see the same issue ...

Jan 30 19:43:11 ip-172-20-37-61 nodeup[846]: I0130 19:43:11.909736     846 changes.go:81] Field changed "Mode" actual="0777" expected="0755"
Jan 30 19:43:11 ip-172-20-37-61 nodeup[846]: I0130 19:43:11.909751     846 changes.go:81] Field changed "Type" actual="symlink" expected="file"
Jan 30 19:43:11 ip-172-20-37-61 nodeup[846]: I0130 19:43:11.909821     846 files.go:50] Writing file "/usr/bin/dockerd"
Jan 30 19:43:11 ip-172-20-37-61 nodeup[846]: I0130 19:43:11.953492     846 changes.go:81] Field changed "Contents" actual="\u007fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00>\x00\x01\x00\x00\x00\xf0\xc7\xe4\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00\x00U\xec\x02\x00\x00\x00\x00\x00\x00\x00\x00@\x008\x00\n\x00@\x00\x1f\x00\x1e\x00\x06\x00\x00\x00\x05\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x000\x02\x00\x00\x00\x00\x00\x000\x02\x00\x00\x00\x00\x00\x00\b\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00p\x02\x00\x00\x00\x00\x00\x00p\x02\x00\x00\x00\x00\x00\x00p\x02\x00\x00\x00\x00\x00\x00\x1c\x00\x00\x00\x00\x00\x00\x00\x1c\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbc/\xe0\x01\x00\x00\x00\x00\xbc/\xe0\x01\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00\xa8;\xe0\x01\x00\x00\x00\x00\xa8;\x00\x02\x00\x00\x00\x00... (truncated)" expected="\u007fELF\x02\x01\x01\x03\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00>\x00\x01\x00\x00\x00\x10\n@\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00\x18\x11\xeb\x01\x00\x00\x00\x00\x00\x00\x00\x00@\x008\x00\x06\x00@\x00\"\x00!\x00\x01\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x12\xf6\x00\x00\x00\x00\x00\x00\x12\xf6\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00\xe8\x18\xf6\x00\x00\x00\x00\x00\xe8\x18V\x01\x00\x00\x00\x00\xe8\x18V\x01\x00\x00\x00\x00y\xf6\xf4\x00\x00\x00\x00\x00\x80\xd0\xf7\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\x90\x01\x00\x00\x00\x00\x00\x00\x90\x01@\x00\x00\x00\x00\x00\x90\x01@\x00\x00\x00\x00\x00\xa8\x00\x00\x00\x00\x00\x00\x00\xa8\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\a\x00\x00\x00\x04\x00\x00\x00\xe8\x18\xf6\x00\x00\x00\x00\x00\xe8\x18V\x01\x00\x00\x00\x00... (truncated)"
Jan 30 19:43:11 ip-172-20-37-61 nodeup[846]: I0130 19:43:11.953661     846 files.go:50] Writing file "/usr/bin/containerd"
Jan 30 19:43:11 ip-172-20-37-61 nodeup[846]: W0130 19:43:11.954079     846 executor.go:139] error running task "File//usr/bin/dockerd" (7m4s remaining to succeed): error copying file "/usr/bin/dockerd": error opening destination file "/usr/bin/dockerd": open /usr/bin/dockerd: text file busy
Jan 30 19:43:11 ip-172-20-37-61 nodeup[846]: W0130 19:43:11.954111     846 executor.go:139] error running task "File//usr/bin/containerd" (7m4s remaining to succeed): error copying file "/usr/bin/containerd": error opening destination file "/usr/bin/containerd": open /usr/bin/containerd: text file busy
Jan 30 19:43:11 ip-172-20-37-61 nodeup[846]: I0130 19:43:11.954121     846 executor.go:155] No progress made, sleeping before retrying 2 task(s)

**Comment by atam003** [comment]
@hakman Looks changes are not picked particular libs are picked from repositories.
I am building my kops using the following doc.
https://kops.sigs.k8s.io/contributing/building/

Can you please help with that?

**Comment by atam003** [comment]
@hakman @justinsb Any update on it. Looks like Nodeup has to be updated in repository with these changes?
