### ISSUE TITLE
Kops /etc/hosts file shows deleted clusters information under "# Begin host entries managed by kops - do not edit".

### ISSUE THREAD

**Issue by prudhvigodithi** [kubernetes/kops#10422]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.16.4

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.16.10

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
ssh into master/worker node and cat /etc/hosts file.

**5. What happened after the commands executed?**
Inside that /etc/hosts file I see cluster information of old deleted clusters, that do not exists.
Example
`10.38.9.93	api.internal.test03.k8s.local etcd-a.internal.test03.k8s.local etcd-events-a.internal.test03.k8s.local`
This above cluster test03.k8s.local we have deleted few weeks back, but inside new cluster we see this entry inside /etc/hosts file.

**6. What did you expect to happen?**
I would assume once we delete the clusters from the state store, next time with kops update, the above entry should be removed from other cluster nodes.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by zetaab** [comment]
I think this isolation was fixed already, could you try newer kops version.

**Comment by prudhvigodithi** [comment]
Hey @zetaab, I still see in /etc/hosts, deleted clusters information, also during startup in logs I see  OnGossip &KVState also shows deleted cluster information
Using kops v1.16.15
