### ISSUE TITLE
nodeup: can't get certificate for kubelet on control plane and workers

### ISSUE THREAD

**Issue by mitch000001** [kubernetes/kops#12007]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.22.0-alpha.1 (git-378a3781a5)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```bash
export KOPS_BASE_URL=https://storage.googleapis.com/kops-ci/bin/1.22.0-alpha.2+378a3781a5
kops create --name dev.kops-master-378a3781a5.k8s.local -f cluster-conf.yaml
kops update cluster --yes
kops validate cluster --wait 30m
```

**5. What happened after the commands executed?**
The cluster did not validate. Kubernetes nodes did not initialize. Kubernetes API server never got reachable.

**6. What did you expect to happen?**
I get a valid and accessible cluster.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-07-16T19:00:05Z"
  name: dev.kops-master-378a3781a5.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  certManager:
    enabled: false
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v2
        createStorageClass: false
        ignore-volume-az: true
        override-volume-az: nova
      loadbalancer:
        floatingNetwork: public
        floatingNetworkID: 12345678-9cc1-4ed0-bbdc-a7476669b4bd
        manageSecurityGroups: true
        method: ROUND_ROBIN
        provider: haproxy
        useOctavia: false
      monitor:
        delay: 1m
        maxRetries: 3
        timeout: 30s
      router:
        externalNetwork: public
  cloudControllerManager:
    clusterName: dev.kops-master-378a3781a5.k8s.local
  cloudProvider: openstack
  configBase: s3://kops-config/dev.kops-master-378a3781a5.k8s.local
  docker:
    registryMirrors:
      - https://pull-through-cache.service.example.com
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - instanceGroup: master-zone-01
          name: etcd-zone-01
          volumeSize: 2
          volumeType: fast-1000
        - instanceGroup: master-zone-02
          name: etcd-zone-02
          volumeSize: 2
          volumeType: fast-1000
        - instanceGroup: master-zone-03
          name: etcd-zone-03
          volumeSize: 2
          volumeType: fast-1000
      manager:
        env:
          - name: ETCD_MANAGER_HOURLY_BACKUPS_RETENTION
            value: 7d
          - name: ETCD_MANAGER_DAILY_BACKUPS_RETENTION
            value: 14d
      memoryRequest: 100Mi
      name: main
      provider: Manager
    - cpuRequest: 100m
      etcdMembers:
        - instanceGroup: master-zone-01
          name: etcd-zone-01
          volumeSize: 2
          volumeType: fast-1000
        - instanceGroup: master-zone-02
          name: etcd-zone-02
          volumeSize: 2
          volumeType: fast-1000
        - instanceGroup: master-zone-03
          name: etcd-zone-03
          volumeSize: 2
          volumeType: fast-1000
      manager:
        env:
          - name: ETCD_MANAGER_HOURLY_BACKUPS_RETENTION
            value: 7d
          - name: ETCD_MANAGER_DAILY_BACKUPS_RETENTION
            value: 14d
      memoryRequest: 100Mi
      name: events
      provider: Manager
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    allowPrivileged: true
    apiAudiences:
      - api
      - istio-ca
    serviceAccountIssuer: kubernetes.default.svc
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
    - 0.0.0.0/0
  kubernetesVersion: 1.18.18
  masterPublicName: api.dev.kops-master-378a3781a5.k8s.local
  metricsServer:
    enabled: true
    insecure: true
  networkCIDR: 10.0.0.0/20
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 0.0.0.0/0
  sshKeyName: dev.kops-master-378a3781a5.k8s.local
  subnets:
    - cidr: 10.0.1.0/24
      name: zone01
      type: Private
      zone: local_zone_01
    - cidr: 10.0.2.0/24
      name: zone02
      type: Private
      zone: local_zone_02
    - cidr: 10.0.3.0/24
      name: zone03
      type: Private
      zone: local_zone_03
    - cidr: 10.0.15.0/29
      name: utility-zone01
      type: Utility
      zone: local_zone_01
  topology:
    bastion:
      bastionPublicName: bastion.dev.kops-master-378a3781a5.k8s.local
    dns:
      type: Private
    masters: private
    nodes: private

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-16T19:00:05Z"
  labels:
    kops.k8s.io/cluster: dev.kops-master-378a3781a5.k8s.local
  name: bastion-zone-01
spec:
  additionalSecurityGroups:
    - dev.kops-master-378a3781a5.k8s.local.monitoring
  additionalUserData:
    - content: |
        #!/bin/bash
        sed -i 's/AllowTcpForwarding no/AllowTcpForwarding yes/' /etc/ssh/sshd_config
        systemctl restart sshd
      name: enable-ssh-agent.sh
      type: text/x-shellscript
    - content: |
        #!/bin/bash
        if [ ! -f /usr/local/bin/node_exporter ]; then
          apt-get update && apt-get install -y curl
          curl -L https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz -o /tmp/node_exporter-0.18.1.linux-amd64.tar.gz
          cd /tmp
          tar xvfz node_exporter-0.18.1.linux-amd64.tar.gz
          mv node_exporter-0.18.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
          rm -r node_exporter-0.18.1.linux-amd64
        else
          echo 'node_exporter already installed.';
        fi;
        systemctl enable node_exporter
        systemctl start node_exporter
      name: install-and-enable-node_exporter.sh
      type: text/x-shellscript
  associatePublicIp: true
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
  image: ubuntu-focal-20-04-amd64-2021-07-01
  machineType: blc.1-2
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: bastion-zone-01
    x-ion.de/wireguard: "true"
  role: Bastion
  subnets:
    - utility-zone01
  zones:
    - local_zone_01

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-16T19:00:05Z"
  labels:
    kops.k8s.io/cluster: dev.kops-master-378a3781a5.k8s.local
  name: master-zone-01
spec:
  additionalSecurityGroups:
    - dev.kops-master-378a3781a5.k8s.local.monitoring
  associatePublicIp: true
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-07-01
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: memory.available<200Mi,nodefs.available<35G,imagefs.available<35G
    evictionSoftGracePeriod: memory.available=30s,nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 70m
      ephemeral-storage: 30G
      memory: 1.4G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.2-6
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: master-zone-01
    x-ion.de/wireguard: "true"
  role: Master
  subnets:
    - zone01
  zones:
    - local_zone_01

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-16T19:00:06Z"
  labels:
    kops.k8s.io/cluster: dev.kops-master-378a3781a5.k8s.local
  name: master-zone-02
spec:
  additionalSecurityGroups:
    - dev.kops-master-378a3781a5.k8s.local.monitoring
  associatePublicIp: true
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-07-01
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: memory.available<200Mi,nodefs.available<35G,imagefs.available<35G
    evictionSoftGracePeriod: memory.available=30s,nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 70m
      ephemeral-storage: 30G
      memory: 1.4G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.2-6
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: master-zone-02
    x-ion.de/wireguard: "true"
  role: Master
  subnets:
    - zone02
  zones:
    - local_zone_02

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-16T19:00:06Z"
  labels:
    kops.k8s.io/cluster: dev.kops-master-378a3781a5.k8s.local
  name: master-zone-03
spec:
  additionalSecurityGroups:
    - dev.kops-master-378a3781a5.k8s.local.monitoring
  associatePublicIp: true
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-07-01
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: memory.available<200Mi,nodefs.available<35G,imagefs.available<35G
    evictionSoftGracePeriod: memory.available=30s,nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 70m
      ephemeral-storage: 30G
      memory: 1.4G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.2-6
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: master-zone-03
    x-ion.de/wireguard: "true"
  role: Master
  subnets:
    - zone03
  zones:
    - local_zone_03

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-16T19:00:06Z"
  labels:
    kops.k8s.io/cluster: dev.kops-master-378a3781a5.k8s.local
  name: node-zone-01
spec:
  additionalSecurityGroups:
    - dev.kops-master-378a3781a5.k8s.local.monitoring
  associatePublicIp: false
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-07-01
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: memory.available<200Mi,nodefs.available<35G,imagefs.available<35G
    evictionSoftGracePeriod: memory.available=30s,nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 70m
      ephemeral-storage: 30G
      memory: 1.4G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.2-6
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: node-zone-01
    x-ion.de/wireguard: "true"
  role: Node
  subnets:
    - zone01
  zones:
    - local_zone_01

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-16T19:00:06Z"
  labels:
    kops.k8s.io/cluster: dev.kops-master-378a3781a5.k8s.local
  name: node-zone-02
spec:
  additionalSecurityGroups:
    - dev.kops-master-378a3781a5.k8s.local.monitoring
  associatePublicIp: false
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-07-01
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: memory.available<200Mi,nodefs.available<35G,imagefs.available<35G
    evictionSoftGracePeriod: memory.available=30s,nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 70m
      ephemeral-storage: 30G
      memory: 1.4G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.2-6
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: node-zone-02
    x-ion.de/wireguard: "true"
  role: Node
  subnets:
    - zone02
  zones:
    - local_zone_02

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-07-16T19:00:06Z"
  labels:
    kops.k8s.io/cluster: dev.kops-master-378a3781a5.k8s.local
  name: node-zone-03
spec:
  additionalSecurityGroups:
    - dev.kops-master-378a3781a5.k8s.local.monitoring
  associatePublicIp: false
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-07-01
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: memory.available<200Mi,nodefs.available<35G,imagefs.available<35G
    evictionSoftGracePeriod: memory.available=30s,nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 70m
      ephemeral-storage: 30G
      memory: 1.4G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.2-6
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: node-zone-03
    x-ion.de/wireguard: "true"
  role: Node
  subnets:
    - zone03
  zones:
    - local_zone_03
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
As the commands itself are not the cause of the problems I'll omit this here.

**9. Anything else do we need to know?**
It seems that the nodes fail to continue with nodeup. Looking into the systemd logs of `kops-configuration.service` I can see the following error message:
```
Jul 17 20:33:35 master-zone-03-mhqqzk nodeup[1993]: I0717 20:33:35.610461    1993 s3fs.go:312] Reading file "s3://kops-config/dev.kops-master-378a3781a5.k8s.local/pki/private/kubelet/keyset.yaml"
Jul 17 20:33:35 master-zone-03-mhqqzk nodeup[1993]: W0717 20:33:35.624776    1993 main.go:133] got error running nodeup (will retry in 30s): error building loader: building *model.KubeletBuilder: keypairID for kubelet missing from NodeupConfig
```
This seems to be coming from this code path: https://github.com/kubernetes/kops/blob/2c3749b3b25511839d60cc10b7bbba95c42856f5/nodeup/pkg/model/context.go#L299

**Comment by johngmyers** [comment]
Fixed by #12002
/close

**Comment by mitch000001** [comment]
I can verify the fix only for the control plane. The worker still don't work.
/reopen

**Comment by jdial1996** [comment]
I think I am having the same issue.  These are the logs I am getting 

```
 nodeup[4036]: I0720 16:44:46.520916    4036 s3fs.go:290] Reading file "s3://<bucket-name>/<cluster-name>/pki/issued/ca/keyset.yaml"
 systemd[1]: run-rb1327a34d78d4eed91e2573a6a143749.scope: Succeeded.
 nodeup[4036]: I0720 16:44:46.534034    4036 s3fs.go:290] Reading file "s3://<bucket-name>/<cluster-name>/pki/issued/kubelet/keyset.yaml"
 nodeup[4036]: I0720 16:44:46.545203    4036 s3fs.go:290] Reading file "s3://<bucket-name>/<cluster-name>/pki/private/kubelet/keyset.yaml"
 nodeup[4036]: W0720 16:44:46.555837    4036 main.go:138] got error running nodeup (will retry in 30s): error building loader: unable to find private key: kubelet

```
Does anyone have any advice as this is preventing me from upgrading to 1.19 clusters.

Thanks,
Jasdeep

**Comment by mitch000001** [comment]
I can confirm that I was able to create a healthy cluster with those changes mentioned.

**Comment by mitch000001** [comment]
@jdial1996 did you also use the proper nodeup binaries? In order to use master you also have to set the `KOPS_BASE_URL` which points to the appropriate nodeup binaries.
You can either compile it yourself and upload it (quite a hassle) or use the builds from the ci. The easiest way to get the latest stable build url from there is to run `curl -s https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt` and set the env var to the result.

**Comment by mitch000001** [comment]
Fixed by #12019
/close
