### ISSUE TITLE
Fix or reduce frequency or switch off perma-failing jobs

### ISSUE THREAD

**Issue by dims** [kubernetes/kops#15468]
Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

| CI Job | Days Failed |
| --- | --- |
|[e2e-kops-aws-cni-calico-ipv6](https://testgrid.k8s.io/google-aws#kops-aws-cni-calico-ipv6)|32|
|[e2e-kops-aws-cni-calico-ipv6-flatcar](https://testgrid.k8s.io/google-aws#kops-aws-cni-calico-ipv6-flatcar)|32|
|[e2e-kops-aws-cni-cilium-ipv6](https://testgrid.k8s.io/google-aws#kops-aws-cni-cilium-ipv6)|32|
|[e2e-kops-aws-external-dns](https://testgrid.k8s.io/google-aws#kops-aws-external-dns)|32|
|[e2e-kops-aws-ipv6-external-dns](https://testgrid.k8s.io/google-aws#kops-aws-ipv6-external-dns)|4|
|[e2e-kops-aws-ipv6-flatcar](https://testgrid.k8s.io/google-aws#kops-aws-ipv6-flatcar)|32|
|[e2e-kops-aws-ipv6-karpenter](https://testgrid.k8s.io/google-aws#kops-aws-ipv6-karpenter)|196|
|[e2e-kops-aws-karpenter](https://testgrid.k8s.io/google-aws#kops-aws-karpenter)|93|
|[e2e-kops-gce-latest](https://testgrid.k8s.io/google-kops-gce#kops-gce-latest)|32| 
|[e2e-kops-gce-leader-migration](https://testgrid.k8s.io/google-kops-gce#kops-leader-migration)|175|
|[e2e-kops-gce-stable](https://testgrid.k8s.io/google-kops-gce#kops-gce-stable)|73| 
|[e2e-kops-grid-cilium-deb10-k25-ko25](https://testgrid.k8s.io/google-aws#kops-grid-cilium-deb10-k25-ko25)|33|
|[e2e-kops-grid-cilium-eni-amzn2-k23](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-amzn2-k23)|187|
|[e2e-kops-grid-cilium-eni-amzn2-k23-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-amzn2-k23-ko26)|155|
|[e2e-kops-grid-cilium-eni-amzn2-k24-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-amzn2-k24-ko26)|162|
|[e2e-kops-grid-cilium-eni-amzn2-k25](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-amzn2-k25)|193|
|[e2e-kops-grid-cilium-eni-amzn2-k25-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-amzn2-k25-ko26 )|159|
|[e2e-kops-grid-cilium-eni-amzn2-k26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-amzn2-k26)|171|
|[e2e-kops-grid-cilium-eni-amzn2-k26-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-amzn2-k26-ko26)|156|
|[e2e-kops-grid-cilium-eni-flatcar-k23](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-flatcar-k23)|72| 
|[e2e-kops-grid-cilium-eni-flatcar-k23-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-flatcar-k23-ko26)|43|
|[e2e-kops-grid-cilium-eni-flatcar-k24-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-flatcar-k24-ko26)|33|
|[e2e-kops-grid-cilium-eni-flatcar-k25-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-flatcar-k25-ko26)|45|
|[e2e-kops-grid-cilium-eni-rhel8-k23](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-rhel8-k23)|193|
|[e2e-kops-grid-cilium-eni-rhel8-k23-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-rhel8-k23-ko26)|161|
|[e2e-kops-grid-cilium-eni-rhel8-k24](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-rhel8-k24)|191|
|[e2e-kops-grid-cilium-eni-rhel8-k25](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-rhel8-k25)|187|
|[e2e-kops-grid-cilium-eni-rhel8-k25-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-rhel8-k25-ko26)|157|
|[e2e-kops-grid-cilium-eni-rhel8-k26-ko26](https://testgrid.k8s.io/google-aws#kops-grid-cilium-eni-rhel8-k26-ko26)|161|
|[e2e-kops-grid-gce-cilium-u2004-k23](https://testgrid.k8s.io/kops-gce#kops-grid-gce-cilium-u2004-k23)|175|
|[e2e-kops-scenario-arm64](https://testgrid.k8s.io/google-aws#kops-scenario-arm64)|33|
|[e2e-kops-scenario-ipv6-terraform](https://testgrid.k8s.io/google-aws#kops-scenario-ipv6-terraform)|33|
|[e2e-kops-scenario-no-irsa](https://testgrid.k8s.io/google-aws#kops-scenario-no-irsa)|32|
|[e2e-kops-scenario-terraform](https://testgrid.k8s.io/google-aws#kops-scenario-terraform)|32|
|[e2e-kops-warm-pool](https://testgrid.k8s.io/google-aws#kops-warm-pool)|110|
|[pull-kops-e2e-aws-upgrade-k123-ko125-to-k124-kolatest-karpenter](https://testgrid.k8s.io/kops-presubmits#pull-kops-e2e-aws-upgrade-k123-ko125-to-k124-kolatest-karpenter)|88|

/kind bug

**Comment by dims** [comment]
cc @justinsb

**Comment by pacoxu** [comment]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/e2e-kops-grid-cilium-eni-u2004-k26 keeps failing after Oct 26. Not sure if this is the right place to raise.

**Comment by justinsb** [comment]
We reviewed the latest "set" of failures in kOps office hours and identified two common causes for a set of failures that started 30 days ago.  (Ginkgo moving from v1 -> v2; deletion of the updown jobs for kOps 1.26).  We're going to remove any remaining kube 1.24 and kOps 1.26 jobs, as those are no longer supported.

Then we can see where we are in terms of other (perhaps more real) failures.

**Comment by rifelpet** [comment]
There is still more triaging to do

/remove-lifecycle stale

**Comment by hakman** [comment]
Most of these should be fixed by at this time. Thanks @rifelpet!

**Comment by dims** [comment]
@hakman @rifelpet here's what i still see:
- https://storage.googleapis.com/k8s-metrics/failures-latest.html?include=kops&sort=days&asc=0
- https://storage.googleapis.com/k8s-metrics/job-health-weekly-latest.html?include=kops&sort=failure_rate&asc=0
