### ISSUE TITLE
API Sever does not start after Server Reboot - kops-cp-utils - Hetzner

### ISSUE THREAD

**Issue by J-Ha** [kubernetes/kops#15818]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.27.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.27.3

**3. What cloud provider are you using?**
Hetzner

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Install a fresh cluster and afterwards reboot, not delete, the ControlPlane Server.

**5. What happened after the commands executed?**
the ControlPlane restarts and the kops-cp-utils cotainer gets recreated, throws the following error:
```
I0824 11:06:21.646714    4049 main.go:30] Copying source file "/ko-app/kops-utils-cp" to target directory "/opt/bin"
F0824 11:06:21.646835    4049 main.go:78] unable to copy source file "/ko-app/kops-utils-cp" to target directory "/opt/bin": unable to create target file "/opt/bin/kops-utils-cp": open /opt/bin/kops-utils-cp: permission denied
```

the result ist, that the etcd don't start and the API Server is not able to connect to the etcd.

**Comment by hakman** [comment]
Thanks for reporting this @J-Ha.
The issue was fixed by https://github.com/kubernetes/kops/pull/15832 and will be available in kOps 1.27.1 soon.

**Comment by Ramprasad-28** [comment]
The issue persists in  kops 1.27.1

Has the changes has been merged? because I see no changes in the script in 1.27.1 branch
