### ISSUE TITLE
kops does not use DOCKER_OPTS or /etc/sysconfig/docker in docker.service

### ISSUE THREAD

**Issue by imsky** [kubernetes/kops#1731]
i'm using kops 1.5 to tweak the storage driver on a cluster and while `/etc/sysconfig/docker` receives the correct flags, `docker.service` does not use that file as an `EnvironmentFile` and does not append `$DOCKER_OPTS` to the main command. this leads to dockerd using devicemapper as the storage driver.

**Comment by chrislovecnm** [comment]
What would you expect?

**Comment by imsky** [comment]
i'd expect that the DOCKER_OPTS are set in the systemd docker service so that changing the storage driver in kops cluster settings actually has an effect

**Comment by justinsb** [comment]
This is fixed in kops 1.5.0, which should release today.

For example, I set:

```
  docker:
    storage: overlay2
```

and docker was run with `/usr/bin/dockerd --ip-masq=false --iptables=false --log-level=warn --storage-driver=overlay2`

(note this is only an example, as overlay2 is not officially supported with k8s 1.5)

Closing; please reopen if not fixed in 1.5.0.

**Comment by imsky** [comment]
@justinsb unfortunately this is not fixed. the systemd service file is correctly generated and the docker version is set correctly, but the storage driver still defaults to devicemapper. restarting the docker service via systemd fixes the issue, but this is something kops should do already.

**Comment by justinsb** [comment]
Ouch - sorry @imsky 

Can you confirm the AMI you are running & the kops version please?

**Comment by justinsb** [comment]
I think this will fix it @imsky  - see the comment for an explanation.

As a simple workaround, if you update the AMI to 1.5, it should "just work".  `kops upgrade cluster` should recommend an image upgrade, I believe; you can either apply it manually or accept its recommendations (it'll probably recommend a k8s upgrade also though).

**Comment by imsky** [comment]
yes @justinsb - after upgrading AMI to 1.5 it worked out of the box

thanks for following up on this
