### ISSUE TITLE
additionalSecurityGroups for bastion ELB in private VPC setup

### ISSUE THREAD

**Issue by kaazoo** [kubernetes/kops#3350]
I need to add an existing security group to the bastion ELB in a private VPC setup. That security group is maintained by another team.

When setting additionalSecurityGroups in the bastion instance group, only the launchconfig of the bastion ASG receives the additonal security group. However as traffic to the bastion comes through the bastion ELB, the additonal security group has to be added to the ELB instead.

There doesn't seem to be an option for this yet.
When I add another security group to the bastion ELB, my changes will be reverted everytime I run 'kops update cluster'.

**Comment by chrislovecnm** [comment]
At this point existing sec groups is not supported. This is a feature that I do want to drop in.  Let me know if you would like to assist!

**Comment by chrislovecnm** [comment]
This is fixed in master closing

**Comment by kaazoo** [comment]
This still doesn't seem to be fixed. In private VPC setup, `additionalSecurityGroups` still only configures the security groups on the bastion instance, not the bastion ELB.

**Comment by kaazoo** [comment]
This still doesn't seem to be fixed. In private VPC setup, `additionalSecurityGroups` still only configures the security groups on the bastion instance, not the bastion ELB.

**Comment by drewib** [comment]
This appears to still be an issue. I don't see a way to even override the elb bastion security group.

**Comment by AdrienKuhn** [comment]
@kaazoo 

I was looking for the same feature.
It seems you can add the following lines to your cluster definition:

```yaml
spec:
  sshAccess:
    - 1.1.1.1/32
    - 2.2.2.2/32
```

This will add the rules to the bastion ELB security group.
