### ISSUE TITLE
S3 bucket location should be configurable

### ISSUE THREAD

**Issue by tazjin** [kubernetes/kops#435]
At the moment kops attemps to figure out the location of the S3 bucket that it stores its state in. In some cases (e.g. if the bucket is in a different AWS account) this will not work, as bucket policies can not grant cross-account access to the `GetBucketLocation` feature.

Kops should have a config flag for this. Setting the flag should skip the explicit check.

**Comment by tazjin** [comment]
This affects `nodeup` as well, so VFS should have some way of passing in the location and then `kops` / `nodeup` have to deal with that somehow.

**Comment by justinsb** [comment]
Agreed - this is also important for GCE support, or if we have KOPS_STATE_STORE be backed by etcd

**Comment by tazjin** [comment]
My particular issue has been solved by the merge of #1247 

@justinsb Do you believe this is still necessary for other cases or should I close?

**Comment by amdonov** [comment]
I think this is still a problem. I'm working in the AWS region us-gov-west-1.

nodeup produces the following error for me.

```
Jul 09 15:58:38 ip-172-20-53-101 nodeup[730]: I0709 15:58:38.440857     730 s3context.go:139] unable to get bucket location from region "us-east-1"; scanning all regions: InvalidToken: The provided token is malformed or otherwise invalid.
Jul 09 15:58:38 ip-172-20-53-101 nodeup[730]: status code: 400, request id: F7AF5225C8796B61
Jul 09 15:58:38 ip-172-20-53-101 nodeup[730]: W0709 15:58:38.882343     730 main.go:141] got error running nodeup (will retry in 30s): error loading Cluster "s3://k8s-gfclab-com-state-store/dpp.k8s.local/cluster.spec": Unable to list AWS regions: AuthFailure: AWS was not able to validate the provided access credentials
Jul 09 15:58:38 ip-172-20-53-101 nodeup[730]: status code: 401, request id: 5f4b15bd-173d-4216-9a46-c1ecc8627aa5
```

To get past the problem, I modified kops-configuration.service to include the AWS region in a environment variable.

/lib/systemd/system/kops-configuration.service
```
[Service]
Environment=AWS_REGION=us-gov-west-1
ExecStart=/var/cache/kubernetes-install/nodeup --conf=/var/cache/kubernetes-install/kube_env.yaml --v=8
Type=oneshot
```

I'd like a better way to do this without needing to log into each node/master.

**Comment by chrislovecnm** [comment]
Some of the work here will impact this https://github.com/kubernetes/kops/pull/2889 - not sure about the approach

**Comment by chrislovecnm** [comment]
Is this still an issue?

**Comment by tazjin** [comment]
Nope!
