### ISSUE TITLE
DNS controller can't initialise "deprecated" credentials provider

### ISSUE THREAD

**Issue by tazjin** [kubernetes/kops#605]
Ran into this while upgrading a 1.3.7 cluster to 1.4, region is `eu-central-1`. It worked fine for a newly created cluster in that region and for an updated cluster in `us-east-1`.

Basically the DNS controller logs are filled with:

```
W1006 13:46:11.110824       1 dnscontroller.go:100] Unexpected error in DNS controller, will retry: error querying for zones: NoCredentialProviders: no valid providers in chain. Deprecated.
    For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by chrislovecnm** [comment]
@tazjin any ideas on this one?

**Comment by kris-nova** [comment]
Just curious - did we `see aws.Config.CredentialsChainVerboseErrors` yet?

**Comment by tazjin** [comment]
@chrislovecnm This particular cases was solved by fiddling with the IAM permissions (I override some of them in the TF output of `kops`).

The problem seems to mostly be that there were no proper error messages for IAM issues. Justin's recent change probably fixed that but I haven't had time to verify.

**Comment by justinsb** [comment]
The "Deprecated" thing is an annoying message ... it actually just means that we haven't set CredentialsChainVerboseErrors.  If we still see this, we need to set it...

**Comment by justinsb** [comment]
(and I'm pretty sure we _don't_ set it for CredentialsChainVerboseErrors, but that might actually need to be fixed in kubernetes/kubernetes once we merge #697)

**Comment by justinsb** [comment]
kops work will be done in #1325; opened https://github.com/kubernetes/kubernetes/issues/39374 for k8s work

**Comment by chrislovecnm** [comment]
Do we need both for a fix?
