### ISSUE TITLE
kops toolbox template: Incorrect interpolation of arrays from values yaml

### ISSUE THREAD

**Issue by cheeseandcereal** [kubernetes/kops#6377]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

    Version 1.11.0

**2. What commands did you run?  What is the simplest way to reproduce this issue?**

    kops toolbox template --values values.yaml --template def.yaml

def.yaml:
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
spec:
  kubernetesApiAccess: {{.allowedIPs}}
```
values.yaml:
```yaml
allowedIPs:
- 1.2.3.4/32
- 4.3.2.1/32
```

**3. What happened after the commands executed?**

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
spec:
  kubernetesApiAccess: [1.2.3.4/32 4.3.2.1/32]
```

**4. What did you expect to happen?**

The interpolated array in the resulting yaml should contain commas to make it a proper yaml array. The way that it's outputting the array in the interpolated outputted yaml is incorrect.

**5. Any other information?**

This also happens when using the --set or --set-string flag with an array as documented in [HERE](https://github.com/kubernetes/kops/blob/master/docs/operations/cluster_template.md), making the documentation incorrect due to this bug.

**Comment by tuxpiper** [comment]
I've come across the same thing, for exactly the same need :)

My 2c is that it would be great if `kops toolbox template` would have a `toYaml` function just like helm does. This is the helm implementation PR: https://github.com/helm/helm/pull/1230

**Comment by drewwells** [comment]
We implemented a helm chart that we then pipe to kops. It looks something like this

```
helm template -f overrides chart/ | kops replace --force -
```

It's neat that kops has some basic templating support. I wonder if it couldn't better leverage `helm` to do the heavy lifting here. That could be as simple as maintaining a helm chart with ClusterSpec and InstanceGroupSpec options ... or as complex as including a lot of the Helm code to give a helm-like experience within kops.

**Comment by Mirio** [comment]
Same issue with Kops 1.13.0

**Comment by cheeseandcereal** [comment]
/reopen
Just checked and this is still an issue in 1.17.0-alpha.1

**Comment by hhaslam11** [comment]
/reopen

still having this issue in `1.19`

**Comment by cheeseandcereal** [comment]
/reopen

this is still an issue

**Comment by rifelpet** [comment]
kOps uses golang's `text/template` packing for templating which renders values according to the [fmt package](https://pkg.go.dev/fmt) which is why you see them missing commas.

kOps also includes the [sprig](https://pkg.go.dev/github.com/Masterminds/sprig/v3) template functions also used by Helm. Sprig's `toJson` function is available and should fit your use-case.

`{{ .allowedIPs | toJson }}` -> `["1.2.3.4/32","4.3.2.1/32"]`

Given that changing the default behavior would be a significant breaking change, I'm inclined to accept this as the workaround and added a docs PR here: https://github.com/kubernetes/kops/pull/12688
