### ISSUE TITLE
Digital Ocean DNS A record for api server not updated with correct IP

### ISSUE THREAD

**Issue by miron9** [kubernetes/kops#8396]
Cluster created in DO doesn't seem to get valid api server IP configured for the following two A records:

```
api.example.co.uk directs to 203.0.113.123
api.internal.example.co.uk directs to 203.0.113.123
```
I deployed the cluster several times now and each time the A record was like above and therefore API server was not accessable via CLI tools. After manual update CLI tools were OK again.

```$ kops version
Version 1.15.0 (git-9992b4055)
```

**Comment by srikiz** [comment]
@miron9 - I was wondering if you continue to see this behavior? I know it takes a while for the DNS to get resolved, and what you see with 203.0.113.123 is a dummy IP that is initially assigned.
FYI - @timoreimann

**Comment by srikiz** [comment]
I just tested on release-1.16 branch and it seems to be working fine.

**Comment by miron9** [comment]
Thanks for getting back to me @srikiz 
I noticed it some time later that those IPs indeed get updated to correct ones but it takes around 10 minutes.

**Comment by srikiz** [comment]
Awesome @miron9 . Thanks ! Can you please close this issue?
FYI - @timoreimann .

**Comment by zak905** [comment]
Hi @srikiz,

I am seeing this issue now, in version `1.23.0` 

not only the `api.internal.example-k8.com` is set to `203.0.113.123`
but also there is no record for `api.internal.example-k8.com`

I have not seen any complaints or errors at creation time, so just wondering.

**Comment by srikiz** [comment]
Hi @zak905 - are you trying this on release-1.23 kops version?

**Comment by zak905** [comment]
Yes, I installed it following the instructions in the docs, so the latest version.

I found out that `dns-controller` is crashing on start up (nil pointer deference issue) while trying to create/upsert the DNS records

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1598205]

goroutine 28 [running]:
k8s.io/kops/dnsprovider/pkg/dnsprovider/providers/do.(*resourceRecordChangeset).applyResourceRecordSet(0xc0002f7dc0, {0x0, 0x0})
	dnsprovider/pkg/dnsprovider/providers/do/dns.go:390 +0x45
k8s.io/kops/dnsprovider/pkg/dnsprovider/providers/do.(*resourceRecordChangeset).Apply(0xc0002f7dc0, {0x1, 0x1})
	dnsprovider/pkg/dnsprovider/providers/do/dns.go:338 +0x525
k8s.io/kops/dns-controller/pkg/dns.(*DNSController).runOnce(0xc000348360)
	dns-controller/pkg/dns/dnscontroller.go:325 +0x112a
k8s.io/kops/dns-controller/pkg/dns.(*DNSController).runWatcher(0xc000348360, 0x0)
	dns-controller/pkg/dns/dnscontroller.go:120 +0x2f
created by k8s.io/kops/dns-controller/pkg/dns.(*DNSController).Run
	dns-controller/pkg/dns/dnscontroller.go:112 +0xc9
```

I think because I am using multiple masters and for some reason the DNS provider for DO fails while trying to update the record, I am investigating further the reasons

**Comment by zak905** [comment]
When I checked the source code, I found out the following:

* This happens when updating/creating records for the private api server, so `api.internal.*`
* For DO case, there are 3 IPs returned (one for each master), so I see this message in the logs: `Adding DNS changes to batch {A api.internal.mydomain.com.} [10.114.0.10 10.114.0.11 10.114.0.12]`
* a nil error happens when calling new here with more than one record https://github.com/kubernetes/kops/blob/master/dnsprovider/pkg/dnsprovider/providers/do/dns.go#L226
* once it returns a nil, the dns controllers upserts a nil value here https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/dns/dnscontroller.go#L588
* finally when the Apply is invoked here https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/dns/dnscontroller.go#L325 the panic happens


The workaround for me was just to create the records manually for both `api.mydomain.com` and `api.internal.mydomain.com` and point them to the load balancer. The thing is there is no internal/private load balancer for DO, so I am wondering if we really need `api.internal.mydomain.com`, maybe this is the source of the issue. 

Anyway, I was wondering if this a bug since DO is still beta.

**Comment by srikiz** [comment]
Thanks. I haven't got a chance to test but wondering if it's an issue with the latest `kops master` branch. May be you should try this on `release-1.23` branch? 
We have our test grid setup for kops DO and it seems to be working fine - https://testgrid.k8s.io/google-aws#e2e-kops-do-calico

**Comment by srikiz** [comment]
Yeah, please open a new issue and I'll take a look at it sometime this week. Thanks !

**Comment by zak905** [comment]
Done: https://github.com/kubernetes/kops/issues/13441

**Comment by pritamfocal** [comment]
I am still facing this issue on version 1.23.0, v1.24.1, 1.25.alpha1...Can you please let me know how can I fix this ? is there way I can add manually if possible...

**Comment by zak905** [comment]
Hi @pritamfocal, 

You can add the DNS records manually by going to the Networking -> Domains -> your domain and then:
- adding an A DNS record for the public api server address: api.{your_cluster_name}.{your_domain} which points to the ip of the load balancer created by kops. Once you do this you will be able to use kubectl to talk to the api server. Could you please check the logs of dns controller pod in the `kube-system` ? also it would be helpful if you can provide the pod info like which container image is user. 
- adding DNS records for the private api server address which is used internally only. To do this, you need to create a record with api.internal.{your_cluster_name}.{your_domain}, the value needs to have the ip address of the kubernetes masters (the three of them separated by a new line)

I have already tried with the changes in #13441  and it worked fine. Not sure, if you have the dns controller latest version

**Comment by pritamfocal** [comment]
Hi @zak905  Thanks for reply...no I tried with almost all versions of kops available from 19 to 25...

I am getting this logs The dns-controller Kubernetes deployment has not updated the Kubernetes cluster’s API DNS entry to the correct IP address. The API DNS IP address is the placeholder address that kops creates: 203.0.113.123. Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate. The protokube container and dns-controller deployment logs may contain more diagnostic information. Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.


I can see in my domains it has added API.(muydomain details) and api.internal.(domain details)...but the API address is same   203.0.113.123...is it fine if I replace this IP with master nodes public IP ?

**Comment by zak905** [comment]
Yes it should be allright. you need to give the `api.{your_cluster_name}.{your_domain}` record the address of the API server load balancer. normally kops create an LB dedicated for the API server, so you should find it under Load Balancers. For the the private one, you can give it directly the address of the master nodes separated by a new line

**Comment by pritamfocal** [comment]
Hi Zak it did not create any loadbalancer...kops create cluster --cloud=digitalocean --name=${ROUTE53_KOPS_DNS} --image=debian-9-x64 --networking=calico --zones=ams3 --ssh-public-key=/Users/pbss/test@sss.pub --node-size=c-4 --node-count=1
I used this command to create cluster

**Comment by pritamfocal** [comment]
and when I gave my master nodes IP address and tried to validate it says connection refused

**Comment by zak905** [comment]
Ok so probably if have not specified `--api-loadbalancer-type=public`, the load balancer will not be created.

Anyway, the most important thing now is to get the logs for the dns-controller pod to be able to troubleshoot. Sometimes, the update of the DNS records takes some time. 

Also, you are using AWS Route 53 as a domain registrar right ? Could you check if you have the NS records in both AWS and DO:
- in DO you should have three NS records with your {domain} name pointing to ns1.digitalocean.com, ns2.digitalocean.com, ns3.digitalocean.com
- in AWS you should have one record with the three  ns1.digitalocean.com, ns2.digitalocean.com, ns3.digitalocean.com as a value separated by a line. It's better to create a dedicated hosted zone to avoid messing up your domain, if you are using it for other things than Kops.

**Comment by pritamfocal** [comment]
Hi Zak, Thanks for your reply... no I am not using anything AWS...I have my domain at godaday and nemservers specified correctly..I tested specifying a test.(mydomain) with A record and IP address to VM it worked...So Domain is properly registered...I tried to use load balancer yesterday but did not have any luck...I tried to access Master node via ssh...and then tried kubectl get pods but kubectl command was not found there ...Do you think something I am doing wrong here ?

**Comment by zak905** [comment]
hard to tell. It could be that the api server is not running ? try checking on the master node using  `ps aux | grep `api-server` for example

**Comment by pritamfocal** [comment]
@zak905 It seems like Api server is running root      3190  0.0  0.0  12716   948 pts/0    S+   18:06   0:00 grep api-server

**Comment by zak905** [comment]
@pritamfocal if it's up and running then you can try to use `kubectl`. Also I suggest we continue this thread on the K8 Slack channel #kops-users. Maybe other users from the community can help as well.
